# Introduction of Machine Learning

In [1]:
import pandas as pd

In [2]:
data2 = pd.read_csv('Titanic_data_cleaned.csv')

In [3]:
data2

Unnamed: 0  PassengerId Survived  Pclass     Sex  Age  \
0             0          343       No       2    male   28   
1             1           76       No       3    male   25   
2             2          641       No       3    male   20   
3             3          568       No       3  female   29   
4             4          672       No       1    male   31   
..          ...          ...      ...     ...     ...  ...   
886         886           10      Yes       2  female   14   
887         887           61       No       3    male   22   
888         888          535       No       3  female   30   
889         889          102       No       3    male   29   
890         890          428      Yes       2  female   19   

     Siblings and spanous  parent and child      Ticket     Fare Embarked  \
0                       0                 0      248740  13.0000        S   
1                       0                 0      348123   7.6500        S   
2                       0                 0      350050   7.8542        S   
3                       0                 4      349909  21.0750        S   
4                       1                 0  F.C. 12750  52.0000        S   
..                    ...               ...         ...      ...      ...   
886                     1                 0      237736  30.0708        C   
887                     0                 0        2669   7.2292        C   
888                     0                 0      315084   8.6625        S   
889                     0                 0      349215   7.8958        S   
890                     0                 0      250655  26.0000        S   

                                                  Name  
0                              Mr.Erik GustafCollander  
1                                 Mr.Sigurd HansenMoen  
2                                  Mr.Hans PederJensen  
3               Mrs.Nils Alma Cornelia BerglundPalsson  
4                                  Mr.ThorntonDavidson  
..                                                 ...  
886                     Mrs.Nicholas Adele AchemNasser  
887                                 Mr.OrsenSirayanian  
888                                   Miss.MarijaCacic  
889                          Mr.Pastcho PentchoPetroff  
890  Miss.Kate Florence Mrs Kate Louise Phillips Ma...  

[891 rows x 12 columns]

In [4]:
data2 = data2.drop('Unnamed: 0', axis=1) #data2.drop(''Unnamed: 0', inplace = False axis=1')

In [5]:
data2

PassengerId Survived  Pclass     Sex  Age  Siblings and spanous  \
0            343       No       2    male   28                     0   
1             76       No       3    male   25                     0   
2            641       No       3    male   20                     0   
3            568       No       3  female   29                     0   
4            672       No       1    male   31                     1   
..           ...      ...     ...     ...  ...                   ...   
886           10      Yes       2  female   14                     1   
887           61       No       3    male   22                     0   
888          535       No       3  female   30                     0   
889          102       No       3    male   29                     0   
890          428      Yes       2  female   19                     0   

     parent and child      Ticket     Fare Embarked  \
0                   0      248740  13.0000        S   
1                   0      348123   7.6500        S   
2                   0      350050   7.8542        S   
3                   4      349909  21.0750        S   
4                   0  F.C. 12750  52.0000        S   
..                ...         ...      ...      ...   
886                 0      237736  30.0708        C   
887                 0        2669   7.2292        C   
888                 0      315084   8.6625        S   
889                 0      349215   7.8958        S   
890                 0      250655  26.0000        S   

                                                  Name  
0                              Mr.Erik GustafCollander  
1                                 Mr.Sigurd HansenMoen  
2                                  Mr.Hans PederJensen  
3               Mrs.Nils Alma Cornelia BerglundPalsson  
4                                  Mr.ThorntonDavidson  
..                                                 ...  
886                     Mrs.Nicholas Adele AchemNasser  
887                                 Mr.OrsenSirayanian  
888                                   Miss.MarijaCacic  
889                          Mr.Pastcho PentchoPetroff  
890  Miss.Kate Florence Mrs Kate Louise Phillips Ma...  

[891 rows x 11 columns]

## relatiopship is how columns interact with each other
#### weak relationship
#### strong relationship
#### weak strong relationship

<h1>Machine Learning</h1>
Machine Learning is a method of data analysis that automated analytical model building. Is a branch of artificail intlligence, base on the idea that system can learn from data, identify patterns and make decision with minimal human intervention.
<h2>Why is machine learning important<h2/>
    <ul>
        <li>Data driven insight</li>
        <li>Predictive analytics</li>
    </ul>
<h2>Types of machine learning<h2/>
<ul>
 <li>Supervised learning: is a type of ML, where the model is trained on label data. the supervision comes from the fact that the model is giving the correct answer during training.</li> 
         <h3>key concept<h3/>
         <li>Label data: it has both input features and output labels. the independent variables that the model use to make reduction are the input features while the dependent variables or target that the model predict is called label</li>
</ul>

## types of supervise learning algorithm
### 1. classification algorithm: that categorise input data into a predefined labels. these simply suggestion that the label or target variables are in category.
### types of classification algorithm:
### 1. logistics regression: is used to predict binary output
### 2. decision tree: it helps to make decision or categorise input into predefine labels but it is not restricted to binary problems

 ### the terms true positive (TP), true negative (TN), false positive (FP), and false negative (FN) are used to describe the outcomes of a classification model's predictions compared to the actual labels in the data. These terms are commonly used to assess the performance of classification algorithms. Here's what each term means:

## True Positive (TP):The model correctly predicted the positive class.Example: The model correctly identifies a person as having a disease when they actually do have it.

## True Negative (TN): The model correctly predicted the negative class. Example: The model correctly identifies a person as not having a disease when they actually do not have it.
## False Positive (FP): The model incorrectly predicted the positive class when it should have predicted negative. Example: The model falsely identifies a healthy person as having the disease.
## False Negative (FN):The model incorrectly predicted the negative class when it should have predicted positive.Example: The model fails to detect a disease in a person who actually has it.
### These terms are essential for evaluating metrics like accuracy, precision, recall, and F1 score, which provide deeper insights into a model’s performance, especially when dealing with imbalanced datasets.

### feature engineering is separating your feature from your label

## "noise" often refers to random or unpredictable variations in data, which can be added to datasets or signals to simulate real-world unpredictability or to test models. You can generate noise in Python using libraries like numpy and random. Here are a few examples of generating different types of noise:

## 1. Gaussian (Normal) Noise: Gaussian noise is often used to simulate random noise in signals or datasets. It follows a normal distribution with a mean (mu) and standard deviation (sigma).

python
Copy
import numpy as np
import matplotlib.pyplot as plt

#### Parameters
mu = 0       # Mean
sigma = 1    # Standard deviation
size = 1000  # Number of samples

#### Generate Gaussian noise
noise = np.random.normal(mu, sigma, size)

#### Visualize the noise
plt.hist(noise, bins=50, density=True)
plt.title('Gaussian Noise')
plt.show()
## 2. Uniform Noise
Uniform noise has equal probability for all values in a specified range. It can be generated using numpy's uniform function.

python
Copy
#### Parameters
low = -1     # Lower bound
high = 1     # Upper bound
size = 1000  # Number of samples

#### Generate Uniform noise
noise = np.random.uniform(low, high, size)

#### Visualize the noise
plt.hist(noise, bins=50, density=True)
plt.title('Uniform Noise')
plt.show()
## 3. Salt and Pepper Noise
Salt and pepper noise randomly replaces some data points with either maximum or minimum values, often used in image processing.

python
Copy
import numpy as np
import matplotlib.pyplot as plt

def salt_and_pepper(image, salt_prob, pepper_prob):
    noisy_image = image.copy()
    
    # Salt noise (white pixels)
    salt_mask = np.random.rand(*image.shape) < salt_prob
    noisy_image[salt_mask] = 1  # Set to maximum value (white)
    
    # Pepper noise (black pixels)
    pepper_mask = np.random.rand(*image.shape) < pepper_prob
    noisy_image[pepper_mask] = 0  # Set to minimum value (black)
    
    return noisy_image

#### Example: Create an image with salt and pepper noise
image = np.zeros((100, 100))  # A black image
noisy_image = salt_and_pepper(image, salt_prob=0.05, pepper_prob=0.05)

#### Visualize the noisy image
plt.imshow(noisy_image, cmap='gray')
plt.title('Salt and Pepper Noise')
plt.show()
## 4. Poisson Noise
Poisson noise is often seen in data related to counting processes, where the variance is proportional to the mean.

python
Copy
#### Parameters
lam = 5   # The expected count (mean)
size = 1000  # Number of samples

#### Generate Poisson noise
noise = np.random.poisson(lam, size)

#### Visualize the noise
plt.hist(noise, bins=30, density=True)
plt.title('Poisson Noise')
plt.show()
## 5. Random Noise using the random module
You can also use Python's built-in random module to add noise in simpler cases, like flipping a coin or generating random numbers.

python
Copy
import random

#### Generate random noise (values between 0 and 1)
noise = [random.random() for _ in range(1000)]

#### Visualize the noise
plt.hist(noise, bins=30, density=True)
plt.title('Random Noise')
plt.show()
Use Cases of Noise:
Simulating real-world data: Adding noise can make datasets more realistic for testing machine learning models.
Image processing: Noise is often added to images for testing algorithms like denoising.
Signal processing: Noise can simulate imperfections in sensor data or communications.
Let me know if you want a deeper dive into any of these types or their applications!

### encoding is changing a data type to the type of data type you want
### nematization is breaking every words to is root
### tokenization is assigning each tokens to is words

# two types of encoding
## label encoding and onehot encoding

In [6]:
### standardization
### tokenization 
### lemmatization
### encoding
### Reshape
### Bias
### Parameter
### inferential stat
### text corpose
### over sampling
### under sampling
### x_train, x_test, y_train, y_test
### trialier and exception

# Evaluation Matrix
## Accuracy : is the percentage of correctly predicted instances out of the total instances. accuracy is important when the data set is roughly balance
   ### True positive + True negative / True positive + True negative + false positive + false negative
## Precision: precision describe the through statement of predicted positive class. it measures how many of the predicted cases were actaully correct. it works for predicted
   ### P = TP / TP + FP
## Recall: it measures how the model finds the actual positive class. it gives the actaul number of the actaul positive of successfuly detected. recall works for actaul.
   ### Recall = TP / TP + FN 
## F1_score = it involves analyzing the precision and recall to create an avearage. ut brings balance between precision and recall
   ### F1_score = (precision * recall/ precision + recall)*2
## Specificity : it measures how many (actual) negative case was actaul predicted. its the opposes of precision
   ### specificity = TN /TN+FP
### Receiver operating characteristics(ROC) and Area under curve(AUC): ROC - it plot True positive verse False positive. AUC - It measures overall model performance. when AUC is =1 (it meams the model is a perfect model, performing very well). when AUC is = 0.5 (it shoes the model takes randoms gueses). when AUC is =< 0.5 (it means the model is performing poorly).

In [7]:
data2

PassengerId Survived  Pclass     Sex  Age  Siblings and spanous  \
0            343       No       2    male   28                     0   
1             76       No       3    male   25                     0   
2            641       No       3    male   20                     0   
3            568       No       3  female   29                     0   
4            672       No       1    male   31                     1   
..           ...      ...     ...     ...  ...                   ...   
886           10      Yes       2  female   14                     1   
887           61       No       3    male   22                     0   
888          535       No       3  female   30                     0   
889          102       No       3    male   29                     0   
890          428      Yes       2  female   19                     0   

     parent and child      Ticket     Fare Embarked  \
0                   0      248740  13.0000        S   
1                   0      348123   7.6500        S   
2                   0      350050   7.8542        S   
3                   4      349909  21.0750        S   
4                   0  F.C. 12750  52.0000        S   
..                ...         ...      ...      ...   
886                 0      237736  30.0708        C   
887                 0        2669   7.2292        C   
888                 0      315084   8.6625        S   
889                 0      349215   7.8958        S   
890                 0      250655  26.0000        S   

                                                  Name  
0                              Mr.Erik GustafCollander  
1                                 Mr.Sigurd HansenMoen  
2                                  Mr.Hans PederJensen  
3               Mrs.Nils Alma Cornelia BerglundPalsson  
4                                  Mr.ThorntonDavidson  
..                                                 ...  
886                     Mrs.Nicholas Adele AchemNasser  
887                                 Mr.OrsenSirayanian  
888                                   Miss.MarijaCacic  
889                          Mr.Pastcho PentchoPetroff  
890  Miss.Kate Florence Mrs Kate Louise Phillips Ma...  

[891 rows x 11 columns]

In [8]:
data2.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Sex', 'Age',
       'Siblings and spanous', 'parent and child', 'Ticket', 'Fare',
       'Embarked', 'Name'],
      dtype='object')

In [9]:
data2.drop(columns = ['Embarked', 'Name', 'Ticket', 'PassengerId'], inplace = True, axis = 1)

In [10]:
data2

Survived  Pclass     Sex  Age  Siblings and spanous  parent and child  \
0         No       2    male   28                     0                 0   
1         No       3    male   25                     0                 0   
2         No       3    male   20                     0                 0   
3         No       3  female   29                     0                 4   
4         No       1    male   31                     1                 0   
..       ...     ...     ...  ...                   ...               ...   
886      Yes       2  female   14                     1                 0   
887       No       3    male   22                     0                 0   
888       No       3  female   30                     0                 0   
889       No       3    male   29                     0                 0   
890      Yes       2  female   19                     0                 0   

        Fare  
0    13.0000  
1     7.6500  
2     7.8542  
3    21.0750  
4    52.0000  
..       ...  
886  30.0708  
887   7.2292  
888   8.6625  
889   7.8958  
890  26.0000  

[891 rows x 7 columns]

In [11]:
data2['Survived'] = data2['Survived'].replace({'Yes': 1, 'No': 0})
data2['Sex'] = data2['Sex'].replace({'male': 1, 'female': 0})

In [12]:
data2

Survived  Pclass  Sex  Age  Siblings and spanous  parent and child  \
0           0       2    1   28                     0                 0   
1           0       3    1   25                     0                 0   
2           0       3    1   20                     0                 0   
3           0       3    0   29                     0                 4   
4           0       1    1   31                     1                 0   
..        ...     ...  ...  ...                   ...               ...   
886         1       2    0   14                     1                 0   
887         0       3    1   22                     0                 0   
888         0       3    0   30                     0                 0   
889         0       3    1   29                     0                 0   
890         1       2    0   19                     0                 0   

        Fare  
0    13.0000  
1     7.6500  
2     7.8542  
3    21.0750  
4    52.0000  
..       ...  
886  30.0708  
887   7.2292  
888   8.6625  
889   7.8958  
890  26.0000  

[891 rows x 7 columns]

In [13]:
# alternative for formula for Encoding
# from sklearn.preprocessing import LabelEncoder

#le = LabelEncoder()
#data2[''] = le.fit_transform(data2[''])

In [14]:
from sklearn.preprocessing import StandardScaler
import numpy as np

sc = StandardScaler()
data2['Fare'] = sc.fit_transform(np.array(data2['Fare']).reshape(-1, 1))

In [15]:
data2

Survived  Pclass  Sex  Age  Siblings and spanous  parent and child  \
0           0       2    1   28                     0                 0   
1           0       3    1   25                     0                 0   
2           0       3    1   20                     0                 0   
3           0       3    0   29                     0                 4   
4           0       1    1   31                     1                 0   
..        ...     ...  ...  ...                   ...               ...   
886         1       2    0   14                     1                 0   
887         0       3    1   22                     0                 0   
888         0       3    0   30                     0                 0   
889         0       3    1   29                     0                 0   
890         1       2    0   19                     0                 0   

         Fare  
0   -0.386671  
1   -0.494391  
2   -0.490280  
3   -0.224083  
4    0.398582  
..        ...  
886 -0.042956  
887 -0.502864  
888 -0.474005  
889 -0.489442  
890 -0.124920  

[891 rows x 7 columns]

In [16]:
data2['Survived'] = data2['Survived'].replace({1:'Yes', 0:'No'})   # changing number to text
data2['Sex'] = data2['Sex'].replace({1:'male', 0:'female'})

In [17]:
data2

Survived  Pclass     Sex  Age  Siblings and spanous  parent and child  \
0         No       2    male   28                     0                 0   
1         No       3    male   25                     0                 0   
2         No       3    male   20                     0                 0   
3         No       3  female   29                     0                 4   
4         No       1    male   31                     1                 0   
..       ...     ...     ...  ...                   ...               ...   
886      Yes       2  female   14                     1                 0   
887       No       3    male   22                     0                 0   
888       No       3  female   30                     0                 0   
889       No       3    male   29                     0                 0   
890      Yes       2  female   19                     0                 0   

         Fare  
0   -0.386671  
1   -0.494391  
2   -0.490280  
3   -0.224083  
4    0.398582  
..        ...  
886 -0.042956  
887 -0.502864  
888 -0.474005  
889 -0.489442  
890 -0.124920  

[891 rows x 7 columns]

In [18]:
data2['Survived'] = data2['Survived'].replace({'Yes': 1, 'No': 0})  # changing text to number 
data2['Sex'] = data2['Sex'].replace({'male': 1, 'female': 0})

In [19]:
data2

Survived  Pclass  Sex  Age  Siblings and spanous  parent and child  \
0           0       2    1   28                     0                 0   
1           0       3    1   25                     0                 0   
2           0       3    1   20                     0                 0   
3           0       3    0   29                     0                 4   
4           0       1    1   31                     1                 0   
..        ...     ...  ...  ...                   ...               ...   
886         1       2    0   14                     1                 0   
887         0       3    1   22                     0                 0   
888         0       3    0   30                     0                 0   
889         0       3    1   29                     0                 0   
890         1       2    0   19                     0                 0   

         Fare  
0   -0.386671  
1   -0.494391  
2   -0.490280  
3   -0.224083  
4    0.398582  
..        ...  
886 -0.042956  
887 -0.502864  
888 -0.474005  
889 -0.489442  
890 -0.124920  

[891 rows x 7 columns]

In [20]:
data2.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'Siblings and spanous',
       'parent and child', 'Fare'],
      dtype='object')

In [21]:
data2 = data2.rename(columns={'Siblings and spanous': 'Siblings_spanous', 
                              'parent and child': 'parent_child'})

In [22]:
x = data2 [['Pclass', 'Sex', 'Age', 'Siblings_spanous', 'parent_child', 'Fare']]
y = data2 ['Survived']

In [23]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 40)

In [24]:
x_train

Pclass  Sex  Age  Siblings_spanous  parent_child      Fare
661       1    1   27                 1             0  0.420730
393       2    0   22                 1             1 -0.064516
266       2    1   36                 0             2 -0.124920
144       2    1   62                 0             0 -0.437007
446       1    0   29                 0             0  3.606793
..      ...  ...  ...               ...           ...       ...
440       1    1   54                 0             1  0.907738
165       3    1    9                 4             2 -0.016444
7         3    0    1                 0             2 -0.331467
219       2    0   44                 1             0 -0.124920
326       1    0   29                 1             0  1.145664

[712 rows x 6 columns]

In [25]:
x_test

Pclass  Sex  Age  Siblings_spanous  parent_child      Fare
246       3    1   28                 2             0 -0.488854
588       1    1   71                 0             0  0.049330
472       1    0   19                 1             0  1.185430
71        3    0   19                 0             0 -0.489776
654       3    1   30                 0             0 -0.502445
..      ...  ...  ...               ...           ...       ...
284       1    0   33                 1             0  1.163700
727       1    0   49                 1             0  0.896497
599       3    0   29                 0             2 -0.341452
525       3    0    2                 0             1 -0.401017
457       1    1   33                 0             0 -0.547748

[179 rows x 6 columns]

In [26]:
y_train

661    1
393    1
266    0
144    1
446    1
      ..
440    0
165    0
7      1
219    0
326    1
Name: Survived, Length: 712, dtype: int64

In [27]:
y_test

246    0
588    0
472    1
71     1
654    0
      ..
284    1
727    1
599    1
525    1
457    0
Name: Survived, Length: 179, dtype: int64

In [28]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(x_train, y_train)

LogisticRegression()

In [29]:
computer_prediction = model.predict(x_test)

In [30]:
computer_prediction

array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0], dtype=int64)

In [31]:
np.array(y_test)

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0], dtype=int64)

In [32]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(computer_prediction, y_test)

In [33]:
accuracy

0.770949720670391

In [34]:
from sklearn.metrics import f1_score

f1 = f1_score(computer_prediction, y_test)

In [35]:
f1

0.7007299270072992

In [36]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(computer_prediction, y_test)

In [37]:
cm

array([[90, 23],
       [18, 48]], dtype=int64)

In [38]:
from sklearn.metrics import r2_score

R2 = r2_score(computer_prediction, y_test)

In [39]:
R2

0.01595602038079924

In [40]:
data2.corr()

Survived    Pclass       Sex       Age  Siblings_spanous  \
Survived          1.000000 -0.338481 -0.543351 -0.067809         -0.035322   
Pclass           -0.338481  1.000000  0.131900 -0.335071          0.083081   
Sex              -0.543351  0.131900  1.000000  0.082533         -0.114631   
Age              -0.067809 -0.335071  0.082533  1.000000         -0.232743   
Siblings_spanous -0.035322  0.083081 -0.114631 -0.232743          1.000000   
parent_child      0.081629  0.018443 -0.245489 -0.176744          0.414838   
Fare              0.257307 -0.549500 -0.182333  0.093856          0.159651   

                  parent_child      Fare  
Survived              0.081629  0.257307  
Pclass                0.018443 -0.549500  
Sex                  -0.245489 -0.182333  
Age                  -0.176744  0.093856  
Siblings_spanous      0.414838  0.159651  
parent_child          1.000000  0.216225  
Fare                  0.216225  1.000000

In [41]:
# decision tree

In [42]:
from sklearn.tree import DecisionTreeClassifier

DTC = DecisionTreeClassifier()
DTC.fit(x_train, y_train)

DecisionTreeClassifier()

In [43]:
result = DTC.predict(x_test)

In [44]:
result

array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0], dtype=int64)

In [45]:
np.array(y_test)

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0], dtype=int64)

In [46]:
from sklearn.metrics import accuracy_score

DTC_accuracy = accuracy_score(result, y_test)

In [47]:
DTC_accuracy

0.8100558659217877

In [48]:
from sklearn.metrics import f1_score

f2 = f1_score(result, y_test)

In [49]:
f2

0.7638888888888888

In [50]:
from sklearn.ensemble import RandomForestClassifier

RFC = RandomForestClassifier()
RFC.fit(x_train, y_train)

RandomForestClassifier()

In [51]:
RFC_result = RFC.predict(x_test)

In [52]:
RFC_result

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0], dtype=int64)

In [53]:
np.array(y_test)

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0], dtype=int64)

In [54]:
from sklearn.metrics import accuracy_score

RFC_accuracy = accuracy_score(RFC_result, y_test)

In [55]:
RFC_accuracy

0.8044692737430168

In [56]:
from sklearn.neighbors import KNeighborsClassifier

KNC = KNeighborsClassifier()
KNC.fit(x_train, y_train)

KNeighborsClassifier()

In [57]:
KNC_result = KNC.predict(x_test)

In [58]:
KNC_result

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1], dtype=int64)

In [59]:
np.array(y_test)

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0], dtype=int64)

In [60]:
from sklearn.metrics import accuracy_score

KNC_accuracy = accuracy_score(KNC_result, y_test)

In [61]:
KNC_accuracy

0.7653631284916201

In [62]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(x_train, y_train)

SVC()

In [63]:
svc_result = svc.predict(x_test)

In [64]:
svc_result

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0], dtype=int64)

In [65]:
np.array(y_test)

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0], dtype=int64)

In [66]:
from sklearn.metrics import accuracy_score

svc_accuracy = accuracy_score(svc_result, y_test)

In [67]:
svc_accuracy

0.6536312849162011

In [68]:
from sklearn.naive_bayes import GaussianNB

GNB = GaussianNB()
GNB.fit(x_train, y_train)

GaussianNB()

In [69]:
GNB_result = GNB.predict(x_test)

In [70]:
GNB_result

array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0], dtype=int64)

In [71]:
np.array(y_test)

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0], dtype=int64)

In [72]:
from sklearn.metrics import accuracy_score

GNB_accuracy = accuracy_score(GNB_result, y_test)

In [73]:
GNB_accuracy

0.776536312849162

In [74]:
print('Enter correct username and password combo to continue')
count = 0

# "" or '' because you are assigning a value string into it
password = ""
username = ""

# looping will continue when wrong input for three times and ask again...
while password!='Hytu76E' and username!='bank_admin' and count < 3:
    # you are collecting user input from CLI separately (you can not assign and operator to such operation as per your code ;)
    username = input("Enter username: ")
    password = input("Enter password: ")

    if password=='Hytu76E' and username=='bank_admin':
     # if match, grand and break
     print('Access granted')
     break

    else:
        print('Access denied. Try again.')
        count+=1     # as per gbse, in the comments, you will need the + to count up

Enter correct username and password combo to continue


Enter username:  gdwjs
Enter password:  dhdffddj


Access denied. Try again.


Enter username:  djfdhdf
Enter password:  dfhfj


Access denied. Try again.


Enter username:  dfjdfhf
Enter password:  dhdfhd


Access denied. Try again.


In [75]:
print('Enter correct username and password combo to continue')
count = 0

# Correct username and password
correct_username = 'bank_admin'
correct_password = 'Hytu76E'

# Loop until the correct credentials are entered or the count reaches 3
while count < 3:
    # Collect user input from CLI
    username = input("Enter username: ")
    password = input("Enter password: ")

    # Check if the entered credentials match the correct ones
    if password == correct_password and username == correct_username:
        print('Access granted')
        break  # Exit the loop if access is granted
    else:
        print('Access denied. Try again.')
        count += 1  # Increment the count of failed attempts

# If the loop ends due to reaching the maximum number of attempts
if count == 3:
    print('Maximum number of attempts reached. Access denied.')

Enter correct username and password combo to continue


Enter username:  sdjfdhf
Enter password:  rjdfl


Access denied. Try again.


Enter username:  dfhfdkdf
Enter password:  dfhfkf


Access denied. Try again.


Enter username:  dfjfdlfd
Enter password:  fdhdr;pfd


Access denied. Try again.
Maximum number of attempts reached. Access denied.


In [76]:
import re

trials = 0

pwd = 2021

pat = "\d{4}"

while trials <= 2:
   	try:
   		t = int(input("Enter password: "))
   		if t == pwd:
   			print("access granted")
   			break
   		elif re.search(pat, str(t)) == None:
   			print("only 4 digits allowed!")
   			trials += 1
   			print("Trial N°", trials)
   		else:
   			print("Access denied")
   			trials += 1
   			print("Trial N°", trials)
   	
   	except ValueError:
   		print("Invalid input! only digits allowed!")
   		trials += 1
   		print("Trial N°", trials)


Enter password:  dhfd


Invalid input! only digits allowed!
Trial N° 1


Enter password:  dhfdl


Invalid input! only digits allowed!
Trial N° 2


Enter password:  djfgkfd


Invalid input! only digits allowed!
Trial N° 3


# Introduction to Regression Analysis

# Types of regression techniques
## 1. Linear regression: is a simple approach for modeling the relationship between depended varaible and independed variables.the model assumes a linear relation betwee the input and output
# Evaluation matrix for Linear regression analysis
## Mean absolute error: This is the avearage absolute differents between the actaul value and predicted value. it gives you an idea of how much and avearge your prediction far much from an actaul value. the value must be close to zero
## mean square error: is similer to MAE, but instead of taking the absolute different it square the different. squaring gives more weight to larger errors. the value mut be close to zero
## root mean square error(RMSE): is the square root of mean square error(SQE). IT BRINGS THE ERROR BACK TO IS ORIGINAL USE OF THE MEASUREMENT. the value must be close to zero
## R square: it tells us how model explain the variance in the data. it ranges from zero to one(0-1). the value must be close to 1
## adjusted R square: the value must be close to zero. it has some similarity with R square 
## 2. polynomail regression: is a more advance form of linear regression that fit a curve line instead of a straight line
## 3. Ridge regression: is a type of linear regression that prevent over fitting by adding a penalty(regularization). it helps when their too many independent variables(multicollinearity: is when two or more independant variables has positive correlation)
## 4. Lasso regression: is similar to rigge regression but completely remove unimportant features instead of reducing their impact.
## regularization: is adding a penalty when when their is over_fitting(lasso regression).
## 5. Elastic Net regression: combination of ridge and lasso regression. when it works, its when you have high correlation between them

In [77]:
data = {'first_name': ['blessing', 'joseph', 'kaite', 'oye', 'bose'], 
        'last_name': ['john', 'patrick', 'tunde', 'emeka', 'seun'], 
        'age': [30, 20, 78, 54, 76], 
        'job_role': ['data analysis', 'reception', 'banker', 'teacher', 'secruity'], 
        'salary': [500000, 300000, 700000, 400000, 600000],
       'Nationality' : ['nigeria', 'south africa', 'togo', 'uk,', 'usa']}

In [78]:
import pandas as pd

In [79]:
Employer = pd.DataFrame(data)

In [80]:
Employer

first_name last_name  age       job_role  salary   Nationality
0   blessing      john   30  data analysis  500000       nigeria
1     joseph   patrick   20      reception  300000  south africa
2      kaite     tunde   78         banker  700000          togo
3        oye     emeka   54        teacher  400000           uk,
4       bose      seun   76       secruity  600000           usa

## Unsupervised learning: Unsupervised learning is a type of machine learning where the model is trained on data that does not have labeled responses. Unlike supervised learning, where the algorithm learns from labeled data (input-output pairs), unsupervised learning algorithms identify patterns, structures, or relationships within the data without any explicit guidance or labeled.

## unsupervised learning algorithm
## 1. clustering: is the process of grouping label data into clusters base on their similarities. the goal of clustering is to identify patterns and relationship in the data without any para knowledge of the data meaning
## clustering algorithmns 
## 1. k_meanings clustering: K-means is an iterative, centroid-based clustering algorithm that partitions a dataset into similar groups based on the distance between their centroids
### 2. hierarchica clustering: is a type of cluster that is done base on the measure of similarity.
#### types of hierarchica clustering
#### 1. agglomerative clustering: this clustering is also called bottom up clustering
#### 2. Divisive clustering : a single cluster breaking it into several cluster

In [81]:
x

Pclass  Sex  Age  Siblings_spanous  parent_child      Fare
0         2    1   28                 0             0 -0.386671
1         3    1   25                 0             0 -0.494391
2         3    1   20                 0             0 -0.490280
3         3    0   29                 0             4 -0.224083
4         1    1   31                 1             0  0.398582
..      ...  ...  ...               ...           ...       ...
886       2    0   14                 1             0 -0.042956
887       3    1   22                 0             0 -0.502864
888       3    0   30                 0             0 -0.474005
889       3    1   29                 0             0 -0.489442
890       2    0   19                 0             0 -0.124920

[891 rows x 6 columns]

In [82]:
#x.columns

In [83]:
x

Pclass  Sex  Age  Siblings_spanous  parent_child      Fare
0         2    1   28                 0             0 -0.386671
1         3    1   25                 0             0 -0.494391
2         3    1   20                 0             0 -0.490280
3         3    0   29                 0             4 -0.224083
4         1    1   31                 1             0  0.398582
..      ...  ...  ...               ...           ...       ...
886       2    0   14                 1             0 -0.042956
887       3    1   22                 0             0 -0.502864
888       3    0   30                 0             0 -0.474005
889       3    1   29                 0             0 -0.489442
890       2    0   19                 0             0 -0.124920

[891 rows x 6 columns]

In [84]:
import joblib

joblib.dump(model, 'Titanic_model_lr.model')

['Titanic_model_lr.model']